tenants:
  - id: 1
    name: "Rogers"
    cameras:
      - id: 1
        name: "Main Area"
        location: "Buijo City Center"
        rtsp_url: "rtsp://admin:abcd1234@200.0.73.70/Streaming/Channels/102"
        fps: 25
        zones:
          - id: 1
            name: "Interior Area"
            metrics: ["people_inside"]
            polygon: [[84, 163], [307, 96], [286, 77], [348, 68], [341, 27], [418, 14], [560, 109], [577, 226], [498, 353], [148, 355], [83, 165]]
            thresholds:
              occupancy: 12
          - id: 2
            name: "Register"
            metrics: ["dwell", "people_inside"]
            polygon: [[107, 156], [144, 249], [230, 215], [215, 121], [107, 151]]
            thresholds:
              dwell: 60  # seconds
              occupancy: 5 # threshold for people inside
      - id: 2
        name: "Drivers Area"
        location: "Buijo City Center"
        rtsp_url: "rtsp://admin:abcd1234@200.0.73.70/Streaming/Channels/202"
        fps: 30
        zones:
          - id: 3
            name: "Drivers Queue"
            metrics: ["people_inside"]
            polygon: [[127, 328], [262, 152], [394, 95], [474, 194], [526, 229], [529, 354], [150, 355], [128, 331]]
            thresholds:
              occupancy: 3
      - id: 4
        name: "Outside Dining Area"
        location: "Buijo City Center"
        rtsp_url: "rtsp://admin:abcd1234@200.0.73.70/Streaming/Channels/702"
        fps: 30
        zones:
          - id: 4
            name: "Dining Area"
            metrics: ["people_inside"]
            polygon: [[93, 226], [404, 44], [563, 60], [493, 352], [130, 349], [92, 229]]
    
      - id: 5
        name: "Break Area"
        location: "Buijo City Center"
        rtsp_url: "rtsp://admin:abcd1234@200.0.73.70/Streaming/Channels/302"
        fps: 30
        zones:
          - id: 5
            name: "Break Area"
            metrics: ["dwell", "people_inside"]
            polygon: [[216, 74], [348, 47], [383, 101], [486, 86], [592, 278], [481, 354], [237, 352], [220, 273], [215, 74]]
            thresholds:
              occupancy: 5

      - id: 6
        name: "Inside Dining Area"
        location: "Buijo City Center"
        rtsp_url: "rtsp://admin:abcd1234@200.0.73.70/Streaming/Channels/1402"
        fps: 30
        zones:
          - id: 6
            name: "Inside Dining Area"
            metrics: ["people_inside"]
            polygon: [[55, 184], [310, 60], [355, 38], [507, 62], [450, 355], [140, 353], [55, 185]]
      - id: 7
        name: "Kitchen Area 1"
        location: "Buijo City Center"
        rtsp_url: "rtsp://admin:abcd1234@200.0.73.70/Streaming/Channels/1302"
        fps: 30
        zones:
          - id: 7
            name: "Kitchen Area 1"
            metrics: ["people_inside"]
            polygon: [[153, 146], [277, 355], [522, 354], [550, 238], [295, 100], [154, 145]]
      - id: 8
        name: "Kitchen Area 2"
        location: "Buijo City Center"
        rtsp_url: "rtsp://admin:abcd1234@200.0.73.70/Streaming/Channels/1602"
        fps: 30
        zones:
          - id: 8
            name: "Kitchen Area 2"
            metrics: ["people_inside"]
            polygon: [[181, 3], [48, 355], [515, 354], [547, 303], [379, 2], [180, 2]]