tenants:
  - id: 1
    name: "Socado"
    store_id: "54f59d0a-be6e-411d-8f9e-1ac505fea992"
    cameras:
      - id: 1
        name: "Cam 1"
        location: "Sucursal X"
        rtsp_url: "rtsp://TryClave:$0c4d02025*@190.153.22.158:554/Streaming/Channels/102"        
        fps: 25
        zones:
          - id: 1
            name: "Zona completa"
            metrics: ["people_inside"]
            polygon: [[0, 0], [1280, 0], [1280, 720], [0, 720]]
            ghost_timeout_minutes: 30